Feature/push notification
Zeroes-Heroes/ChatAPI pull request #23
Opened 2024-12-26 15:05 UTC by NikolaySlavov-96

2025-01-17 18:44 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                Route = "Chats",
In all places where there is a "Route" with just a string next to it, I would like to extract it and make it more readable, but I don't know how. The idea is that it needs to be a string. This is necessary so that when a notification is opened, the phone knows which screen to take the user to.

2025-01-19 14:08 UTC, NaumVitanov requested changes
It seems like the for cycle is being misused, it would be best to discuss that problem. I see that you have ignored some nullable warnings. Is this intentional? I think there is a mixup with the business logic for when to send notifications and when not. I find it only logical to send a notification when a user is offline, but I see in the code that you have used the reversed logic.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                Route = "Chats",
Create a string const in a static class and use it everywhere you need it.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/Chat/Service/ChatService.cs
> +		notificationDispatch.NotificationForNewCreateChat(createChatRequest.UserIds, chatCreatorId, chatEntity.Id);
NotificationForNewChat

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                Body = $"{userName} created chat with you",
Put a dot at the end of the sentence.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            for (int i = 0; i < chatParticipantIds.Count(); i++)
![image](https://github.com/user-attachments/assets/785c5712-b713-4fa6-b867-fece64d0ec71)

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                if (i != chatCreatorId)
This check will try to see if the number of the current iteration of the cycle is equal to the chatCreatorId. If you are not sure what I mean let's talk it over.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    bool isUserOnline = await IsUserOnline(i);
You are checking if the number of current iteration of the cycle is online.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    if (!isUserOnline)
You're check is reversed here. If the user is offline we want to send the notification and if he is online, then we want to skip (return Result.Success())

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            for (int i = 0; i < chatParticipantIds.Count(); i++)
It would be better to use foreach here.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/Extensions/ServiceCollectionExtension.cs
> +			.AddTransient<IAppleTokenService, AppleTokenService>()
Why did you make those services transient?

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    await SendNotification(i, notificationBody);
When calling that in a cycle you are making a new db request each time, because inside you call the FetchEnabledUserDeviceDataById method.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/Friendship/Service/FriendshipService.cs
> +				notificationDispatch.NotificationForAcceptFriendship(senderUserId, targetUserId);
You could remove the "For" part of the send notification method names, it would still be understandable if it's just NotificationAcceptedFriendship

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            await appleService.SendAsyncPushNotification(deviceToken, payload);
This method could return success or failure but you are not handling it. If you do not need to know the result, why are you returning it then?

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    ChatId = notificationInfo?.ChatId.ToString()
If the comment is correct, then in the situation when you have not provided the chatId, the ToString method will throw a null reference exception.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +        {
You are using this method in a cycle, but inside the method you call another method which makes a request to the db. This should be optimized.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    await SendPushNotificationToApple(deviceToken, notificationBody);
put a "continue", after the sending of the notification in order to skip the execution of the code since we know if it has gotten to this point it doesn't need to go further.

2025-01-19 14:08 UTC, NaumVitanov commented on Services/Token/Service/AppleTokenService.cs
> +            using var ecdsa = GetEcdsaParametersFromPrivateKey(privateKeyText);
Use explicit types please.

2025-03-25 18:08 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    if (!isUserOnline)
Don't get me wrong—I might be mistaken—but this check returns true or false.

In this case, if the user is in the cache, it will return true, and if they are not, it will return false.
However, my logic is that if the user is in the cache, they shouldn’t receive a notification because they are considered online. If they are not in the cache, they should receive a notification because they are considered offline.

2025-03-25 18:12 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                if (i != chatCreatorId)
Thanks, Yes, right now I will only check by index, and I need to get the ID from the index.

2025-03-25 18:15 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    await SendNotification(i, notificationBody);
Correct, what is your suggestion?

2025-03-25 18:23 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            await appleService.SendAsyncPushNotification(deviceToken, payload);
I'm returning a result in case we might need it at some point, but in reality, it's not necessary.

After all, we don’t want to stop the logic just because of an issue on Apple’s side preventing the notification from being sent.

2025-03-25 18:28 UTC, NikolaySlavov-96 commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +        {
Your comments are often very helpful, and I learn a lot from them. However, could you try to consolidate your logic and all relevant information into a single comment?

For this particular line, I’ve had to read at least three different comments, and I’m not entirely sure what you meant. In one case, you suggest discussing it, while in another, you simply state it as a fact... 😃

2025-04-05 18:11 UTC, vgechev reviewed
Folder name - NotificationDispatchService, why not just Notifications?

2025-04-05 18:11 UTC, vgechev commented on Services/Extensions/ServiceCollectionExtension.cs
> +			.AddTransient<IAppleService, AppleService>()
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Interface/IAppleService.cs
> +        Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload);
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +        public async Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload)
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +            HttpClient httpClient = new HttpClient();
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +        // TODO (Moved)
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    // if (!isUserOnline) return;
.

2025-04-05 18:11 UTC, vgechev commented on .dockerignore
> +AuthKey_*
are u sure u need these lines?

2025-04-05 18:11 UTC, vgechev commented on Services/Chat/Interface/IChatService.cs
> +	Task<Result> CreateChat(CreateChatRequest createChatRequestModel, int chatCreatorId);
why not in the DTO?

2025-04-05 18:11 UTC, vgechev commented on Services/Chat/Service/ChatService.cs
> +		notificationDispatch.NotificationForNewChat(createChatRequest.UserIds, chatCreatorId, chatEntity.Id);
-entities

2025-04-05 18:11 UTC, vgechev commented on Services/Extensions/ServiceCollectionExtension.cs
> +			.AddTransient<IAppleService, AppleService>()
Lifetime, why

2025-04-05 18:11 UTC, vgechev commented on Services/Extensions/ServiceCollectionExtension.cs
> +		// TODO: Review the try {} catch block to either improve its error handling logic or remove it if unnecessary
.

2025-04-05 18:11 UTC, vgechev commented on Services/Friendship/Service/FriendshipService.cs
> +		notificationDispatch.NotificationForNewFriendshipRequest(targetUser.Id, senderUser.Name);
Dispatch**er***

2025-04-05 18:11 UTC, vgechev commented on Services/Friendship/Service/FriendshipService.cs
> +		notificationDispatch.NotificationForNewFriendshipRequest(targetUser.Id, senderUser.Name);
phone => receiverPhone

2025-04-05 18:11 UTC, vgechev commented on Services/Friendship/Service/FriendshipService.cs
> +		switch (newStatus)
extract, await , try catch

2025-04-05 18:11 UTC, vgechev commented on Services/Hubs/BaseHub.cs
> +			// Send a notification to each user participating in the chat, excluding the user who sender the message
I think i saw this comment multiple times. You can just add it as a method summary and it will be clear everywhere what this is doing.

2025-04-05 18:11 UTC, vgechev commented on Services/Hubs/BaseHub.cs
> +			notificationDispatch.NotificationForNewMessage(receiversIds, senderId, sendMessageEvent.Content, chatId);
possible DTO

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Interface/IAppleService.cs
> +        Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload);
async in name

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Interface/INotificationDispatch.cs
> +        Task<Result> NotificationForNewMessage(int[] receiversIds, int senderUserId, string message, int chatId);
possible dto

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Models/AppleNotificationPayload.cs
> +namespace Services.NotificationDispatch.Models;
DTO's, no? 

Also, records (immutable)

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Models/DeviceDataResponse.cs
> +namespace Services.NotificationDispatch.Models;
dtos

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Models/DeviceUserDataResponse.cs
> +public class DeviceUserDataResponse
possible inheritance

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Models/NotificationBody.cs
> +public class NotificationBody
Body? Payload? Nothing?

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +        public async Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload)
Async

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +        public async Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload)
deviceToken could be in DTo

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +            HttpClient httpClient = new HttpClient();
inject

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +            var request = new HttpRequestMessage(HttpMethod.Post, apnUrl)
this works, but im sure there was a simpler way with less code

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +            if (response.IsSuccessStatusCode)
no need for the if, becuase the line above will throw and this will not be reached.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/AppleService.cs
> +                return Result.Failure($"Failed to send notification: {response.StatusCode}, {responseBody}");
who are we returning this to? also i dont think its a good idea to return the response body

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            await appleService.SendAsyncPushNotification(deviceToken, payload);
YAGNI principle

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    ChatId = notificationInfo?.ChatId?.ToString() ?? string.Empty,
this nullability check wont be reached because if it's null, it will throw above.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +                    {"chatId", notificationInfo?.ChatId.ToString()}
same here

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            return Result.Success();
.

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            List<DeviceDataResponse> result = await deviceNotificationConfigRepo.FetchEnabledUserDeviceDataById(userId);
This is not a response

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +        public async Task<Result> NotificationForNewMessage(int[] receiversIds, int senderUserId, string message, int chatId)
I'm pretty sure we can figure out how to make only one method and pass an enum of the notificationType and dynamically add the message and title. We can dive deeper on a call

2025-04-05 18:11 UTC, vgechev commented on Services/NotificationDispatchService/Service/NotificationDispatchService.cs
> +            return Result.Success();
You are returning a result in a lot of places, but not using it. No need to do that when it's internal calls. Only when you need to give a proper response to the FE.

2025-04-05 18:11 UTC, vgechev commented on Services/Friendship/Service/FriendshipService.cs
> +				notificationDispatch.NotificationForBlockedFriendship(senderUserId, targetUserId);
these are not awaited

2025-04-05 18:11 UTC, vgechev commented on Services/Friendship/Service/FriendshipService.cs
> +		notificationDispatch.NotificationForNewFriendshipRequest(targetUser.Id, senderUser.Name);
**not awaited**

2025-04-05 18:11 UTC, vgechev commented on Services/Token/Interface/IAppleTokenService.cs
> +	Task<string> GetPushNotificationToken();
Im a bit confused. Why do you need the interface and the class?

2025-04-05 18:11 UTC, vgechev commented on Services/Utilities/Models/AppSettings.cs
> +	public string ApplePrivateKeyPath { get; set; }
you can split this into multiple classes and sections and get only what you need, no need to have everything in one place. (first of SOLID)

2025-04-05 19:58 UTC, vgechev commented on Services/Token/Service/AppleTokenService.cs
> +            return Task.FromResult(tokenString);
.

2025-04-05 19:58 UTC, vgechev commented on Services/NotificationDispatchService/Models/DeviceDataResponse.cs
> +public class DeviceDataResponse
response

2025-04-06 05:33 UTC, NikolaySlavov-96 commented on Services/Token/Service/AppleTokenService.cs
> +            return Task.FromResult(tokenString);
?

2025-04-06 14:17 UTC, NaumVitanov commented on Services/NotificationDispatchService/Interface/IAppleService.cs
> +        Task<Result> SendAsyncPushNotification(string deviceToken, AppleNotificationPayload payload);
To write good quality code one would follow the convention, which is to write Async at the end of an async method.

2025-04-06 14:27 UTC, NaumVitanov approved these changes
Good job! I think you have addressed all the critical points.

2025-06-20 18:30 UTC, merged