Subscribe push notification
Zeroes-Heroes/ChatAPI pull request #24
Opened 2024-12-31 21:34 UTC by NikolaySlavov-96

2025-01-02 13:08 UTC, NaumVitanov reviewed
Good job! Could use some improvements. Details about the PR comments: Some of the comments I will be writing only once, but they will be applicable to more than one place. Please check your whole logic according to all of my comments. E.g. when I type a comment about using explicit types, it applies to the whole project not just this line. Another example is the naming of a table. If I write it should be plural that applies to everywhere it is used not only where my comment is.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Configurations/OperationSystemEntityConfiguration.cs
> +            builder.ToTable("OperationSystem");
The table name should be plural.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/OperationSystemEntity.cs
> +
We should not be leaving warnings like this one. It opens up the possibility for bugs.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Context/AppDbContext.cs
> +	public DbSet<OperationSystemEntity> OperationSystem { get; set; }
Both table names should be in plural, here and in the config of each entity.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public bool IsTurnOnNotification { get; set; }
"Enabled" would be better for the naming of that property. If you do not find it descriptive enough, you can make it "NotificationEnabled" or even better write a short summary above it to explain what it does.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public virtual UserEntity? User { get; set; }
Why is the user nullable? You are setting the userId from the constructor is it possible for this property to be null?

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Seeders/Seeds/OperationSystemSeeder.cs
> +                var entity = new List<OperationSystemEntity>
Use explicit types and then you can make it "= new()". That's the approach used in the project.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +                .HasPrincipalKey(e => e.Id)
This method is written ONLY for clarity in this case. When using the primary key as a connection there is no need to call that method.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public int OS { get; set; }
This should be named OsId. Please follow the convention.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public PushNotificationEntity(int oS, string token, bool IsTurnOnNotification, int UserId, int deviceId)
This naming suggest that each row in the table will hold one push notification. If I understand the logic correctly, this entity and table hold the configurations of a push notification settings for a given device. Please name the entity accordingly, or correct me if I am wrong about the logic here.

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +                .HasPrincipalKey<UserDeviceEntity>(e => e.Id)
This looks strange to me. Why do we have to specify the entity for the FK and the PK in one to one relationship, but with one to many we do not have to specify it? Are we missing something or is there no other way to do that?

2025-01-02 13:08 UTC, NaumVitanov commented on Database/Entities/UserDeviceEntity.cs
> +	public virtual PushNotificationEntity? PushNotification { get; set; }
Why is there no config for this virtual property? How is the connection made?

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Extensions/ClaimsPrincipalExtensions.cs
> +		return deviceId ?? throw new ArgumentNullException("Could not extract user Device ID from token");
Please fix the message to be in the same style as the other one for the user id. It would look something like this:

"Could not extract device id from token"

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Extensions/ClaimsPrincipalExtensions.cs
> +	public static readonly string DeviceId = "http://schemas.yourapp.com/claims/deviceid";
Can you make this as an extension to the the ClaimTypes class?

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            OperationSystemEntity result = await dbContext.OperationSystem.FirstOrDefaultAsync(o => o.TypeOS == operationSystem);
This should be nullable.

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            throw new NotImplementedException();
That should be implemented. It should actually be implemented in a base repo which should be inherited by this repo, because it's needed in every repo abstraction possible

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            await SaveChangesAsync();
How are you handling the logic if this row throws when saving?

2025-01-02 13:08 UTC, NaumVitanov commented on Services/PushNotification/Models/ChangeStatusRequest.cs
> +public record ChangeStatusRequest(bool IsNotificationStatus);
Change this property with the same name as the one I suggested for the DB property. -  "Enabled"

2025-01-02 13:08 UTC, NaumVitanov commented on Services/PushNotification/Models/PushNotificationResponseDeviceData.cs
> +public record PushNotificationResponseDeviceData(bool IsTurnOnNotification);
Same naming as the two before

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            dbContext.PushNotification.AnyAsync(p => p.Token == notificationDTO.Token && p.UserId == userId);
The naming of the method is wrong. It checks if there is a token for the given user, not if the token exists for any user.

2025-01-02 13:08 UTC, NaumVitanov commented on Services/Repositories/User/Repository/UserRepository.cs
> +	public Task<UserDeviceEntity?> GetIdByDeviceId(string deviceId) =>
Wrong naming. You are getting the device by the deviceId, not Id by the deviceId as you have written

2025-01-02 13:08 UTC, NaumVitanov commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("Device Id doesn't exists");
I do not think the FE (the user) needs so much details in the errors. Leave fewer errors which combine the different scenarios.

2025-01-02 13:08 UTC, NaumVitanov commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity notificationEntity = new(operationSystemId.Value, deviceData.Token, IsTurnOnNotification: true, UserId: userId, userDevice.Id);
You have a relation between the devices and the notifications, also you have a relation between the OS and the notification (using the OS itself). You can get all of that info in one request to the DB instead of three separate ones.

2025-01-02 16:38 UTC, NikolaySlavov-96 commented on Database/Entities/PushNotificationEntity.cs
> +        public int OS { get; set; }
In this case, if I name it "Os," would you understand in two months that it refers to the commonly accepted name for an operating system, or would you wonder what is meant?

2025-01-02 16:41 UTC, NikolaySlavov-96 commented on Database/Entities/PushNotificationEntity.cs
> +        public PushNotificationEntity(int oS, string token, bool IsTurnOnNotification, int UserId, int deviceId)
How would you like me to name it?

2025-01-02 16:51 UTC, NikolaySlavov-96 commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            await SaveChangesAsync();
Based on the code that exists in this project, I don't see anywhere where such a type of error is being caught. If you mean a "try-catch" block, I don't think that would be necessary because an error will be returned to the service, and it will, in turn, return it to the controller, which will return something other than "success" to the user.

2025-01-02 17:00 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("Device Id doesn't exists");
Yes, the user does not need this message, but I think it is necessary for easier understanding of the problem in special cases. In the case when you have only one general message for a problem with only one specific user ID, it would be much harder to find the problem on their phone compared to if we have a clear and precise message about where things went wrong.

2025-01-02 17:07 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity notificationEntity = new(operationSystemId.Value, deviceData.Token, IsTurnOnNotification: true, UserId: userId, userDevice.Id);
I'm sorry, I don't understand you. In this case, before creating a record, I check if the data exists, and if it does, I return a descriptive and precise error, and I also ensure that data duplication does not occur. If you mean to just make one query and add several "&&", for me, it becomes too complicated. I like simple things.

2025-01-02 17:11 UTC, NikolaySlavov-96 commented on Services/Repositories/User/Repository/UserRepository.cs
> +	public Task<UserDeviceEntity?> GetIdByDeviceId(string deviceId) =>
Oooo. Thanks!

2025-01-02 17:18 UTC, NikolaySlavov-96 commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            throw new NotImplementedException();
Please verify!

2025-01-02 17:19 UTC, NikolaySlavov-96 commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            OperationSystemEntity result = await dbContext.OperationSystem.FirstOrDefaultAsync(o => o.TypeOS == operationSystem);
What do you mean?

2025-01-02 17:22 UTC, NikolaySlavov-96 commented on Database/Entities/UserDeviceEntity.cs
> +	public virtual PushNotificationEntity? PushNotification { get; set; }
Can you give me guidance on how to configure it?

2025-01-03 19:55 UTC, vgechev requested changes
1. The seeding code should not be part of the normal app execution as this can cause concurrency issues when multiple instances are running and would also require the app having permission to modify the database schema, if needed. Since the seed is very small, you could've just made it in the OnModelCreating method, example:
![image](https://github.com/user-attachments/assets/00cfd407-bfd6-457d-800f-179485a69e89)


Or if you want to make it more abstract, you could create a class with the seed data, an extenstion method (e.g. called Seed) to ModelBuilder (the param from OnModelCreating) and just call modelBuilder.Seed() in the OnModelCreating method. This way it will be very clean, I can provide examples if you want, but I'm sure a quick google search will show you the same result.
The solution with these seeders is more confusing and also you are calling "SaveChanges" which should be a red flag because in seeding you should not be calling it. P.S. you should usually use the Async method for SaveChanges =).

There is a third option, you can do it in the migration directly, like so:
![image](https://github.com/user-attachments/assets/3937c25c-cc17-4e7a-9d0f-92d92e39fc9f)



2. Honestly, I'm kind of confused why you would even need the OperationSystem table since it will probably only have 2, at most 3, records and you could've easily just used an enum instead. I don't see any benefit in creating a table.

3. The naming of some of the classes and params can be improved. I haven't commented all of them, please review.

4. This is a question for everyone - shouldn't the repositories be in the Database project?

2025-01-03 19:55 UTC, vgechev commented on Database/Configurations/OperationSystemEntityConfiguration.cs
> +    internal class OperationSystemEntityConfiguration : IEntityTypeConfiguration<OperationSystemEntity>
"Entity" as part of the name is redundant. It's only clutter, same goes for Configuration. You can easily see it's a config from the namespace.

2025-01-03 19:55 UTC, vgechev commented on Database/Configurations/OperationSystemEntityConfiguration.cs
> +        public void Configure(EntityTypeBuilder<OperationSystemEntity> builder)
Entity in the name is redundant here as well.

2025-01-03 19:55 UTC, vgechev commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +    internal class PushNotificationEntityConfiguration : IEntityTypeConfiguration<PushNotificationEntity>
same here (naming).

2025-01-03 19:55 UTC, vgechev commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +        public void Configure(EntityTypeBuilder<PushNotificationEntity> builder)
same here (naming).

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/OperationSystemEntity.cs
> +        public OperationSystemEntity(string typeOS)
possible use of expression

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/OperationSystemEntity.cs
> +        [Required]
Let's be consistent and use a single way of defining required properties. I can see in other cases we are using the configuration classes to define these:

![image](https://github.com/user-attachments/assets/7d3c6295-6604-45a1-a7c1-0c4f150b4480)

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/PushNotificationEntity.cs
> +        public PushNotificationEntity(int oS, string token, bool IsNotificationEnabled, int UserId, int deviceId)
os is better than oS, IMO, and operatingSystem is the best.

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/PushNotificationEntity.cs
> +        public int OS { get; set; }
I'm not sure why you are shortening it at all. You can call it `OperatingSystemId`

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/OperationSystemEntity.cs
> +            TypeOS = typeOS;
OSType, or even better - OperatinglSystemType

2025-01-03 19:55 UTC, vgechev commented on Database/Entities/PushNotificationEntity.cs
> +        [Required]
. (refer to prev comment)

2025-01-03 19:55 UTC, vgechev commented on Database/Migrations/20241231094258_addPushNotificationWithSeparateTableFroNames.cs
> +                name: "OperationSystem",
It's usually called "Operating system" not *operation* system.

2025-01-03 19:55 UTC, vgechev commented on Services/Extensions/ClaimsPrincipalExtensions.cs
> +	public static readonly string DeviceId = "http://schemas.yourapp.com/claims/deviceid";
Is this really the best name for this claim?

2025-01-03 19:55 UTC, vgechev commented on Services/Extensions/ServiceCollectionExtension.cs
> +			.AddTransient<ISeeder, OperationSystemSeeder>()
.

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result> SubscribeForPushNotification(PushNotificationDTO deviceData, int userId, string deviceId)
"deviceData" i love how you simplified and shortened the name here, but in the interface it's different and longer. This one is better, or you can even use only "data".

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +            bool checkDeviceTokenExists = await pushNotificationRepo.CheckDeviceTokenExists(deviceData, userId);
I prefer "Does Device Token Exist"

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +        public Task<bool> CheckDeviceTokenExists(PushNotificationDTO notificationDTO, int userId) =>
I prefer "Does Device Token Exist". Also, why are you passing the whole dto when you are expecting only the token, it makes no sense.

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("This Device token already exists");
I don't understand the logic here. Why do we have device tokens? Why are we checking for them, etc..?
Please, let's start writing summaries and comments and explanations in the code. This way everyone will be on the same page and we'll have fewer questions.

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("Device Id doesn't exists");
Shouldn't we check first if the device exists and then for a token for it?

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result> SubscribeForPushNotification(PushNotificationDTO deviceData, int userId, string deviceId)
You are using a DTO with only two properties, why? Either include all the parameters in it and just pass the DTO or remove the DTO and pass 4 params. I don't understand the point of splitting it like so.

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure($"This operating system {deviceData.OS} is not maintained");
is not supported*

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +            }
When you have multiple checks (more than 1, imo), I think it's way better to just extract them in a method, call it ValidateData or whatever, which returns an array of errors or the first validation error it hits, and then in the calling method to check if there are any errors returned from the ValidateData method and if so, return Result.Failure(errors). It will improve the readability by a lot.

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity notificationEntity = new(operationSystemId.Value, deviceData.Token, IsNotificationEnabled: true, UserId: userId, userDevice.Id);
no need to have "UserId: ", just pass the userId

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("No data found or new record is the same with old record");
.. is the same **as**  old ..

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity? result = await pushNotificationRepo.UpdateDeviceData(userId, deviceId, request.IsNotificationEnabled);
Isn't it better if this method returns a boolean instead? Just true if successful, false if not. Why do you need the whole entity (tracked)?

2025-01-03 19:55 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result<PushNotificationResponseDeviceData>> GetPushNotificationData(string deviceId, int userId)
What is happening here? Why are you using and passing the whole entity again when you only need a boolean in the end, to check whether or not the notification is enabled for that user and device? Don't use entities like this, for nothing, they're very expensive in terms of resources, especially when they are tracked by the db context.

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            return notificationEntity;
Why are you returning the entity here? You are not using it anywhere. KISS and YAGNI principles apply here.

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            return notificationData;
Same here, refer to my previous comment.

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +        public Task<PushNotificationEntity?> GetPushNotificationIdByDeviceId(string deviceId, int userId)
Rename to IsNotificationEnabledForDeviceId( ... ) and make a .Select to return only what you need - a boolean.

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +        public Task SaveChangesAsync() =>
you have savechanges, but are also calling saveChanges separately in the methods..? Why?

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            OperationSystemEntity result = await dbContext.OperationSystems.FirstOrDefaultAsync(o => o.TypeOS == operationSystem);
There is a warning here. Add ? to OperationSystemEntity, like so `OperationSystemEntity?`

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            if (result != null)
you can remove the IF and shorten the whole part of the code to just this:

OperationSystemEntity? entity = ....;
return result?.Id;

2025-01-03 19:55 UTC, vgechev commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            if (result != null)
And again, I have no idea why you wouldn't just use an ENUM instead. It would simplify the code by a lot.

2025-01-03 19:55 UTC, vgechev commented on Turbo/Controllers/PushNotification/Controller/PushNotificationController.cs
> +            if (result.IsSuccess)
Just a suggestion - I'm pretty sure we can make a middleware to handle this and not have to duplicate these "if (isSuccess) ... else ..."

2025-01-03 19:55 UTC, vgechev commented on Turbo/Program.cs
> +			seederRunner.RunSeeders(context);
no :D

2025-01-03 21:37 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public int OS { get; set; }
I agree with Valentino here. On the other hand, even if we leave it at Os, we can write a summary of the property which will then be available every time someone puts the cursor on the property anywhere in the code. Both ways it will be understandable.

2025-01-03 21:45 UTC, NaumVitanov commented on Database/Entities/PushNotificationEntity.cs
> +        public PushNotificationEntity(int oS, string token, bool IsTurnOnNotification, int UserId, int deviceId)
I purposefully did not suggest a name. My idea was for you think of an appropriate one. In the sake of answering your question, here is a suggestion for the naming, which is not perfect but a bit more accurate: DeviceNotificationConfigEntity

2025-01-03 21:46 UTC, NaumVitanov commented on Database/Entities/UserDeviceEntity.cs
> +	public virtual PushNotificationEntity? PushNotification { get; set; }
Yes, let's do that over a call, if it's ok with you.

2025-01-03 21:49 UTC, NaumVitanov commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            OperationSystemEntity result = await dbContext.OperationSystem.FirstOrDefaultAsync(o => o.TypeOS == operationSystem);
Since the project uses nullable annotations and warnings, this object of type OperationSystemEntity should be nullable. FirstOrDefault, could return null, hence the nullable type. It would look like that:  OperationSystemEntity? result = await dbContext.OperationSystem.FirstOrDefaultAsync. Please notice the question mark added after the class.

2025-01-03 21:51 UTC, NaumVitanov commented on Services/Repositories/OperationSystem/Repository/OperationSystemRepository.cs
> +            throw new NotImplementedException();
Could you please clarify what type of verification is needed here? We could do it over a call, for easier communication.

2025-01-03 21:54 UTC, NaumVitanov commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            await SaveChangesAsync();
I do not say that because of how anywhere else in the project this type of case is handled.  At the time of writing this comment it seemed to me, that if we leave it like that, a possibility for a problem is left open. When looking at the code again, I see that you are right to say that the normal flow will handle it good enough.

2025-01-03 21:55 UTC, NaumVitanov commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("Device Id doesn't exists");
Aren't these messages used only to be send to the FE or am I missing something here? Those are not the error logs...

2025-01-03 21:56 UTC, NaumVitanov commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity notificationEntity = new(operationSystemId.Value, deviceData.Token, IsTurnOnNotification: true, UserId: userId, userDevice.Id);
Simple is good! Maybe my idea is overcomplicating things here. Good one :)

2025-01-04 07:12 UTC, NikolaySlavov-96 commented on Database/Entities/OperationSystemEntity.cs
> +        [Required]
In this project, given its small size, i have noticed at least three approaches to working with the database. Util there is a clarified way of working that will be used. consider this comment as skipped.

2025-01-04 07:14 UTC, NikolaySlavov-96 commented on Services/Extensions/ClaimsPrincipalExtensions.cs
> +	public static readonly string DeviceId = "http://schemas.yourapp.com/claims/deviceid";
What would be a better name for this?

2025-01-04 07:15 UTC, NikolaySlavov-96 commented on Services/Extensions/ServiceCollectionExtension.cs
> +			.AddTransient<ISeeder, OperationSystemSeeder>()
What should "." convey?

2025-01-04 07:29 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("This Device token already exists");
I understand that you want to describe how the entire process works, what Apple and Android need to know in order to understand whom to send a notification. Why do we actually need to check if the same user is trying, for some reason, to subscribe with the same device twice?

2025-01-04 07:34 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result> SubscribeForPushNotification(PushNotificationDTO deviceData, int userId, string deviceId)
I thought that what comes and is expected from the body of the request is more appropriate to be separated from the things that are taken from the "accessToken" itself and passed internally.

2025-01-04 07:42 UTC, NikolaySlavov-96 commented
@vgechev Thank you very much for the comments. I learned a lot of useful things. Those with which i agree will be changed very soon. For the others on which there is a comment, i expect a resolution before doing anything.

2025-01-04 07:46 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("Device Id doesn't exists");
I was under the impression that if something like "Sentry" is used in the future, we could more easy understand  what the problem was between the backend and frontend.

2025-01-04 17:57 UTC, NikolaySlavov-96 commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +                .HasPrincipalKey(e => e.Id)
We will discuss it in the conversation.

2025-01-04 17:59 UTC, NikolaySlavov-96 commented on Database/Entities/PushNotificationEntity.cs
> +        public int OS { get; set; }
OperatingSystemType OperatingSystem. 💯

2025-01-04 18:11 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result> SubscribeForPushNotification(PushNotificationDTO deviceData, int userId, string deviceId)
I don't understand which interface you are talking about that has a different name

2025-01-04 18:12 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +            bool checkDeviceTokenExists = await pushNotificationRepo.CheckDeviceTokenExists(deviceData, userId);
This is the name I used the first time @NaumVitanov

2025-01-04 18:20 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity? result = await pushNotificationRepo.UpdateDeviceData(userId, deviceId, request.IsNotificationEnabled);
After the changes made, we no longer need it. Thank you very much for your attentiveness.

2025-01-04 18:31 UTC, NikolaySlavov-96 commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            return notificationEntity;
Thank you very much for your attentiveness.

2025-01-04 18:39 UTC, NikolaySlavov-96 commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +        public Task SaveChangesAsync() =>
Apparently, I am quite unfamiliar. We will discuss it when we talk.

2025-01-04 18:42 UTC, NikolaySlavov-96 commented on Turbo/Controllers/PushNotification/Controller/PushNotificationController.cs
> +            if (result.IsSuccess)
I agree with you, but i am following the other controllers. If it is devised to make the change, we will create a PR specifically for this change, and it will be applied.

2025-01-06 17:17 UTC, vgechev commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result<PushNotificationResponseDeviceData>> GetPushNotificationData(string deviceId, int userId)
dbContext.PushNotifc.Where(x => x...).Select(x => x...).SingleOrDefaultAsync();

2025-01-06 17:50 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +        public async Task<Result> SubscribeForPushNotification(PushNotificationDTO deviceData, int userId, string deviceId)
At this moment i think that this way it would be readable, and i will keep it this way.

2025-01-06 17:53 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +                return Result.Failure("This Device token already exists");
In "PushNotificationDTO" i'm adding description of what the two properties mean.

2025-01-06 19:21 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +            }
At this moment i think that this way it would be readable, and i will keep it this way.

2025-01-06 19:30 UTC, NikolaySlavov-96 commented on Services/PushNotification/Service/PushNotificationService.cs
> +            PushNotificationEntity notificationEntity = new(operationSystemId.Value, deviceData.Token, IsTurnOnNotification: true, UserId: userId, userDevice.Id);
Please check!

2025-01-06 19:32 UTC, NikolaySlavov-96 commented on Services/Repositories/PushNotification/Repository/PushNotificationRepository.cs
> +            dbContext.PushNotification.AnyAsync(p => p.Token == notificationDTO.Token && p.UserId == userId);
Done!

2025-01-06 19:36 UTC, NikolaySlavov-96 commented on Database/Configurations/PushNotificationEntityConfiguration.cs
> +                .HasPrincipalKey<UserDeviceEntity>(e => e.Id)
The conversation in "Telegram" about which approach to keep and which will continue in the project.

2025-01-06 19:40 UTC, NikolaySlavov-96 commented on Database/Entities/PushNotificationEntity.cs
> +        public PushNotificationEntity(int oS, string token, bool IsTurnOnNotification, int UserId, int deviceId)
How do you feel about remaining all of this in the other PR that is for integrating the sending of notifications?

2025-01-11 11:02 UTC, NaumVitanov commented on Services/Repositories/DeviceNotificationConfig/Repository/DeviceNotificationConfigRepository.cs
> +        public Task<bool> IsTokenExistsForUser(string deviceToken, int userId) =>
This way it's grammatically incorrect. DoesTokenExistForUser, would be correct, even though it does not follow the "Is,Has" pattern for booleans

2025-01-11 11:02 UTC, NaumVitanov commented on Services/DeviceNotificationConfigService/Service/DeviceNotificationConfigService.cs
> +            int userDeviceId = await userRepo.GetDeviceByDeviceId(deviceId);
The naming of the method is wrong. Please change it to show that it's getting the userDeviceId

2025-01-11 11:28 UTC, NaumVitanov approved these changes
Thanks for complying with our requests! Good job!

2025-01-11 11:29 UTC, merged